name: '[autorelease] On PR merged'

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:
    inputs:
      fake-version:
        description: 'Fake version number (e.g. 1.0.0) for testing'
        required: false

jobs:
  init:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'autorelease') || github.event_name == 'workflow_dispatch'
    outputs:
      build-version: ${{ steps.set_tag.outputs.build-version }}
      tag-version: ${{ steps.set_tag.outputs.tag-version }}
      is-prerelease: ${{ steps.semver_parser.outputs.prerelease == 'true' }}
      release-notes: ${{ steps.get-release-info.outputs.release-notes }}
    steps:
      - uses: actions/checkout@v4

      - name: Get latest release info
        id: get-release-info
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: query
          version: latest

      - name: Display release notes
        run: |
          echo "${{ steps.get-release-info.outputs.release-notes }}"

      - name: Parse current version number
        id: semver_parser
        uses: madhead/semver-utils@v4
        with:
          version: ${{ steps.get-release-info.outputs.version }}

      - name: Set build and tag version
        id: set_tag
        run: |
          raw='${{ inputs.fake-version || steps.get-release-info.outputs.version }}'
          build_version="${raw#v}"
          tag_version="v${build_version}"
          echo "build-version=$build_version" >> $GITHUB_OUTPUT
          echo "tag-version=$tag_version" >> $GITHUB_OUTPUT

  build:
    if: (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'autorelease')) || github.event_name == 'workflow_dispatch'
    needs: init
    uses: ./.github/workflows/build-and-test.yml
    with:
      build-version: ${{ needs.init.outputs.tag-version }}
      create-container: true

  create_release:
    needs:
      - init
      - build
    runs-on: ubuntu-latest
    if: (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'autorelease')) || github.event_name == 'workflow_dispatch'
    steps:
      - name: Create Draft Release
        id: create_draft_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.init.outputs.tag-version }}
          name: Release ${{ needs.init.outputs.build-version }}
          body: ${{ needs.init.outputs.release-notes }}
          draft: true
          prerelease: ${{ needs.init.outputs.is-prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display instructions
        run: |
          echo "::notice title=Draft Release Prepared::A draft release has been prepared. Publish it to trigger pushing the container to Docker Hub: ${{ steps.create_draft_release.outputs.html_url }}"
